### ISSUE TITLE
Transfer of a file with an apostrophe in the file name fails with a HIERARCHY_ERROR error message

### ISSUE THREAD

**Issue by ingridbr** [irods/irods_client_globus_connector#101]
# Bug Report 

## iRODS and Globus, OS and Version

iRODS server 4.3.1 almalinux9 
Globus Connect server version: globus-connect-server, package 5.4.67, cli 1.0.46
Globus irods connector: irods-gridftp-client-4.3.1.0-16.x86_64

## What did you try to do?

I tried to transfer a file that contains an apostroph in the file name  from a Globus Personal connect endpoint to an irods globus endpoint using the Globus graphical interface

![image](https://github.com/irods/irods_client_globus_connector/assets/6448876/a345592b-a5f0-44ac-9ab8-c3a55216d01c)

## Expected behavior 

The file gets uploaded without errors 

## Observed behavior (including steps to reproduce, if applicable)

When transferring a file names "Ingrid's test file.txt" the transfer fails with the following error: 

Error (transfer)
Endpoint: VSC iRODS gbiomed.irods.icts.kuleuven.be (e1074609-2279-4c5c-95a2-8fcfbb44ae5e)
Server: 134.58.8.4:443
File: /gbiomed/home/u0089722/test/Ingrid%27s%20test%20file.txt
Command: STOR /gbiomed/home/u0089722/test/Ingrid's test file.txt
Message: Fatal FTP response
---
Details: 500-Command failed. : iRODS: Error: rcDataObjOpen failed opening '/gbiomed/home/u0089722/test/Ingrid's test file.txt'\r\n500-. HIERARCHY_ERROR: , status: -1803000.\r\n500-\r\n500 End.\r\n

The same file can be transferred without errors to a Globus endpoint on a POSIX system.
An iput of the same file with the name quoted or with the apostrophe escaped also works and the file is uploaded to irods:

$ iput "Ingrid's test file.txt"
$ ils
/zone/home/user/test:
  Ingrid's test file.txt

**Comment by JustinKyleJames** [comment]
I will debug this and see if it is in fact the same as 3902.

**Comment by ingridbr** [comment]
Thank you Justin!

**Comment by korydraughn** [comment]
@JustinKyleJames If you confirm it's irods/irods#3902, try compiling https://github.com/irods/irods/pull/7819 and seeing if it resolves the issue. Even with that PR, you may have to tweak the logic in the globus connector slightly. It shouldn't require anything more than replacing embedded single quotes with their hex encoding.

**Comment by JustinKyleJames** [comment]
I was able to upload and download a test with an apostrophe using globus-url-copy.

```
root@cd28fc7627dd:/# globus-url-copy justin\'s\ test.txt gsiftp://$(hostname):2811/tempZone/home/rods/justin\'s\ test.txt
root@cd28fc7627dd:/# ils
/tempZone/home/rods:
  justin's test.txt
root@cd28fc7627dd:/# globus-url-copy gsiftp://$(hostname):2811/tempZone/home/rods/justin\'s\ test.txt justin\'s\ test.txt.2
root@cd28fc7627dd:/# ls -l justin\'s\ test.txt.2 
-rw-r--r-- 1 root root 15 Jun 27 17:25 "justin's test.txt.2"
```
I'm wondering if this has to do with checksum processing?

**Comment by JustinKyleJames** [comment]
I tested this with iRODS built https://github.com/irods/irods/pull/7819 (also rebuilt the globus plugin with the iRODS dev package from this pull) and it worked.

I'm still not sure why is always worked with globus-url-copy but not with ftp but it definitely appears to be related to  https://github.com/irods/irods/issues/3902.

**Comment by JustinKyleJames** [comment]
I figured out what the difference is between the two scenarios.

In the globus-url-copy scenario, the `transfer_info->alloc_size` is being sent.  Because of this and because the file size is small, it was only doing one open/write/close.

In the ftp scenario, this `transfer_info->alloc_size` is not provided so we use the number of threads from the configuration.  This means that after the initial open there are other opens that use the replica token.  This must trigger a code path that uses genQuery and this error.

Also note that if I set `$numberOfIrodsReadWriteThreads 1` in /etc/gridftp.conf, the error does not occur when using FTP.

@ingridbr Would it be possible for you confirm this workaround on your side?

**Comment by JustinKyleJames** [comment]
One possible work-around that is less invasive than the one above is to force only one thread if we encounter an apostrophe in the filename.  It is a hack but the target is very limited.  Thoughts?

**Comment by trel** [comment]
I think a workaround is fine - so it works.

and then make a new issue pointing back here for the 'real' fix later so we don't forget.

**Comment by korydraughn** [comment]
@JustinKyleJames Please close if completed.

**Comment by JustinKyleJames** [comment]
> @JustinKyleJames Please close if completed.

Are we ok in saying that this will only be implemented in main?  (Note we do not have a 4-3-stable branch.)

**Comment by korydraughn** [comment]
Because this is only a client, yes.

Have you identified a need for a 4-3-stable branch?

**Comment by JustinKyleJames** [comment]
> Because this is only a client, yes.
> 
> Have you identified a need for a 4-3-stable branch?

No.  At this time main is essentially 4-3-stable.
