### ISSUE TITLE
Update services.irods.deploy.resources.limits.cpus in docker-compose to be a string rather than an int.

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_client_globus_connector#108]
After upgrading my version of docker-compose, it was error out because `services.irods.deploy.resources.limits.cpus` was an int.  Puting single quotes around the number fixes this.

**Comment by alanking** [comment]
@JustinKyleJames - Please close if complete. Thanks

**Comment by JustinKyleJames** [comment]
Close as it is merged.
