### ISSUE TITLE
Overwriting a file does not update its modify time

### ISSUE THREAD

**Issue by michaellink** [irods/irods_client_globus_connector#45]
- [x] main
- [x] 4-2-stable
---
When overwriting an existing file with the DSI, the modification time is not updated.  One problem this leads to is that the previously cached checksum metadata is considered current, instead of calculating a new one.

I reproduced this on 4.2.11.1, and confirmed that iput does update the modification time.

Mike

**Comment by trel** [comment]
Good find.  We'll get a test around that.

**Comment by JustinKyleJames** [comment]
I am working on this.  Should have a fix soon.

**Comment by kurtmckee** [comment]
Thanks @JustinKyleJames!

**Comment by kurtmckee** [comment]
@JustinKyleJames and @alanking, I just noticed that a fix was pushed to the `4-2-stable` branch. Thank you both for your work on this!
