### ISSUE TITLE
Request for new release containing the modification time issue patch

### ISSUE THREAD

**Issue by ingridbr** [irods/irods_client_globus_connector#54]
Would it be possible to make a new release of this plugin containing the  fix for the modification patch issue.
We need to deploy it because some users are hitting this issue and they are waiting for the fix.
Having a new release will make our live easier. 

Thank you!

**Comment by alanking** [comment]
I think 4.2.11.1 is all but ready to release but we are waiting on a couple of small things to get tied up. Most of our recent efforts in this project had been on preparing for a release that is compatible with iRODS 4.3.x.

@JustinKyleJames or @trel will hopefully have more to add :)

**Comment by trel** [comment]
we did it!

https://github.com/irods/irods_client_globus_connector/releases/tag/4.2.11.2

**Comment by trel** [comment]
referring to https://github.com/irods/irods_client_globus_connector/issues/45
