### ISSUE TITLE
Checksum timeout errors when transferring data to and from 4.3.0 globus irods endpoints

### ISSUE THREAD

**Issue by ingridbr** [irods/irods_client_globus_connector#55]
### iRODS Version, OS and connector Version

- iRODS server 4.3.0 and 4.2.11
- globus connect server: package 5.4.52, cli 1.0.34
- irods-gridftp-client-4.2.11.2-1 (the latest available)

All iRODS collections (4.3.0 and 4.2.11) are using the same globus endpoint. 

### What did you try to do?

We have been using  for a while the Globus iRODS connector without major issues with a number of iRODS zones. We recently upgraded all zones except one to iRODS v4.3.0 and since then we have problems when transferring files with the checksum check activated (default mode in Globus) for the zones running iRODS 4.3.0 . The zone still running 4.2.11 is working fine.

### Expected behavior

Transfers will be successful to/from Globus iRODS collections when checksum check is activated (default Globus mode)

### Observed behavior (including steps to reproduce, if applicable)

This is what we have observed:

* The problem seems to appear with transfers involving multiple files not for single file transfers.
* The problem occurs both when the iRODS 4.3.0 endpoint is the source or the destination.
* When deactivating checksum check (check “do NOT verify file integrity after transfer”) transfers are done without errors.
* The same dataset transferred to/from an iRODS 4.2.11 works fine

The error in Globus interface is:

Error (transfer) Endpoint: VSC iRODS set.irods.icts.kuleuven.be (56dd39e2-ffae-4075-8354-ba8ed078dd59) Server: 134.58.8.37:443 Command: CKSM MD5 0 -1 /set/home/u0089722/Globus-tests/test-dataset/100MB.bin Message: The operation timed out --- Details: Timeout waiting for response

We have managed to reproduce the error with a test dataset with the following files:

1MB.bin 5MB.bin 10MB.bin 50MB.bin 100MB.bin 500MB.bin 1GB.bin 5GB.bin 10GB.bin   

Where each file has been generated using the command:

dd if=/dev/urandom of=256GB.bin bs=1M count=X iflag=fullblock

and X is 1 5 10 50 100 500 1000 5000 10000 respectively.

In attachment (globus_irods_checksum_timeout.log) you can find the filtered gridftp.log of the transfer when debug log level was activated.  Globus taskID : 1b14b91c-b786-11ed-a505-1f2a3a60e896

[globus_irods_chechsum_timeout.log](https://github.com/irods/irods_client_globus_connector/files/10869486/globus_irods_chechsum_timeout.log)

We opened an issue to Globus support for the problem and they told us: 

*Our devs have taken a look at the outputs provided, and it appears that the process is hanging after computing the checksum while attempting to update the checksum metadata on the iRODS server. You'll want to discuss this further with iRODS support*

**Comment by korydraughn** [comment]
Thanks for reporting this. We'll investigate.

**Comment by JustinKyleJames** [comment]
The checksum operation has been recently updated for 4.3.  This has not yet been released.  We will have to push this out ASAP.

**Comment by ingridbr** [comment]
ok. Thank you! We'll be waiting for the release

**Comment by JustinKyleJames** [comment]
This was a bit more complicated than I originally thought but we have a fix for it.  If you are interested in getting a version of the package to test on I can provide it.  I would just need the OS version.

**Comment by alanking** [comment]
Related to #50

@JustinKyleJames - Should we close this as completed?

@trel / @korydraughn - Should we kick off the release machinery as of this issue?

**Comment by trel** [comment]
i think this is the only known thing to get the 4.3.0.0 release tagged

**Comment by JustinKyleJames** [comment]
> Related to #50
> 
> @JustinKyleJames - Should we close this as completed?
> 
> @trel / @korydraughn - Should we kick off the release machinery as of this issue?

I don't think so as the real fix will be in 4.3.1.

**Comment by JustinKyleJames** [comment]
> > Related to #50
> > @JustinKyleJames - Should we close this as completed?
> > @trel / @korydraughn - Should we kick off the release machinery as of this issue?
> 
> I don't think so as the real fix will be in 4.3.1.

Actually on second thought, yes, it should be closed.  The moving of these into the plugin is only valid for 4.3.0.  In 4.3.1 we will use the version that is namespaced in iRODS core.

**Comment by JustinKyleJames** [comment]
Deleted my previous comment as I thought it was about issue 50.  Should we let Ingrid test it before closing?

**Comment by trel** [comment]
#57 is the last one remaining.   Closing this as complete.
