### ISSUE TITLE
Update README for building plugin with latest Globus version

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_client_globus_connector#59]
- [x] main
- [x] 4-3-0-stable
- [x] 4-2-stable
---

Update README for building plugin with latest Globus version

**Comment by alanking** [comment]
Will this change apply for all 3 branches (main, 4-3-0-stable, and 4-2-stable)?

**Comment by JustinKyleJames** [comment]
This was merged into 4-2-stable.  Closing.
