### ISSUE TITLE
Deprecation error when compiling Globus plugin on Ubuntu 22

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_client_globus_connector#76]
When compiling Globus plugin on Ubuntu 22 I got deprecation warnings for the following methods:

- MD5_Init
- MD5_Update
- MD5_Final
- SHA1_Init
- SHA1_Update
- SHA1_Final
- SHA256_Init
- SHA256_Update
- SHA256_Final
- SHA512_Init
- SHA512_Update
- SHA512_Final

To work around this error I had to disable the -Werror flag.  After doing so it built and tests passed.

We need to update these methods as described here: https://www.openssl.org/docs/man3.1/man3/SHA512_Update.html

Note that irods core uses some of these methods.  I think that the -Werror flag isn't enabled for those.

**Comment by alanking** [comment]
Similar problems were encountered in irods/irods. Consider doing something similar to this: https://github.com/irods/irods/commit/aa7d3ea852f21bbf41c9a2dfa4b1b3dd9931bbee

**Comment by alanking** [comment]
@JustinKyleJames - Please close if complete. Thanks

**Comment by JustinKyleJames** [comment]
closing this issue.
