### ISSUE TITLE
globus_connector doesn't contain the client name/identifier - spOption

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_globus_connector#83]
Would it be possible to add spOption for identifying `irods_client_globus_connector` as the client that connects to the iRODS server?

Because in our rules we cannot capture the globus connector as client in the `rei` object of PEPs.

for example the snippet below writes out an empty string:

```
def pep_api_data_obj_close_post(rule_args, callback, rei):
    items = dict(session_vars.get_map(rei).items())
    callback.writeLine("serverLog", f"{items['connection']['option']}")
```

**Comment by korydraughn** [comment]
I believe what you're asking for is possible.

We'll investigate.

**Comment by JustinKyleJames** [comment]
Putting the following in /etc/gridftp.conf will handle that for you.

```
$spOption irods_client_globus_connector
```
I did that and then made a connection and did an ips and it reported the process as expected.

Let me know if that would be sufficient and if so I'll update the README.

**Comment by JustinKyleJames** [comment]
Question from @korydraughn is if this should be hardcoded to `irods_client_globus_connector` or if it should be modifiable (as it is now).  I am not sure which is preferred.

**Comment by mstfdkmn** [comment]
Thanks @JustinKyleJames. After we made your above mentioned configuration change, I could capture "globus" as the client that connects to the iRODS server. So yes, this is sufficient for us.

**Comment by korydraughn** [comment]
Good.

@JustinKyleJames Let's go with updating the README. No hard-coded value necessary.

**Comment by alanking** [comment]
@JustinKyleJames - Please close if complete

**Comment by korydraughn** [comment]
If there's no reason to introduce a 4-3-stable branch at this time, that's perfectly ok.

**Comment by JustinKyleJames** [comment]
I don't see a reason to have it now.  When we do create it we will create it from the current branch so it will have this README change.
