### ISSUE TITLE
Create tests for other operating systems for the Globus container.

### ISSUE THREAD

**Issue by JustinKyleJames** [irods/irods_client_globus_connector#95]
Create tests for other operating systems for the Globus container.

- Ubuntu 20
- Debian 11
- Debian 12
- Centos 7

**Comment by trel** [comment]
Ub18 is EOL - let's remove it.

**Comment by JustinKyleJames** [comment]
> Ub18 is EOL - let's remove it.

Will do.

**Comment by alanking** [comment]
@JustinKyleJames - Please close if complete. Thanks

**Comment by JustinKyleJames** [comment]
Closing
